---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
```{r}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo=FALSE )  # comment
```


```{r, message=FALSE, Warning = FALSE, echo=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(readxl)
library(readr)
library(janitor)
library(plotly)
library(countrycode)
library(see)
library(extrafont)
library(stringi)
library(kableExtra)
library(sparkline)
library(formattable)
```

```{r}
# Font selected: 
my_font <- "Courier New"
# Colors selected: 
my_colors <- c("#3E606F", "#8C3F4D")
my_theme <- function(...){
  theme_abyss() + 
    theme(plot.margin = unit(c(1, 2, 1, 1), "cm")) + 
    theme(plot.title = element_text(size = 22, family = my_font)) + 
    theme(plot.subtitle = element_text(size = 13, family = my_font)) + 
    theme(plot.caption  = element_text(size = 12, family = my_font)) + 
    theme(axis.text = element_text(family = my_font, size = 13)) + 
    theme(panel.grid.major.y = element_blank())
}
```

```{r}
ins_companies <- read_excel("ins_companies.xlsx")
states <- read_csv("states.csv")
```


```{r}
ins_companies %>% 
  clean_names() %>% 
  na.omit() ->dt_ins
glimpse(dt_ins)
```
```{r}
dt_ins %>% 
  mutate(hover = paste0(name,"\n founded in ",country, ", ", year_founded)) %>% 
  plot_ly(x= ~year_founded,
          y= ~current_employee_estimate) %>% 
   add_trace(text = ~hover,
            hoverinfo ="text") %>% 
  layout(title = 'Number of employees and year founded',
         xaxis = list(title = "Year founded"),
         yaxis = list(title = "Number of employees"))
  
```
```{r}
dt_ins %>% 
  count(country) %>% 
  arrange(desc(n)) -> dt_ins_map
code<-countrycode(dt_ins_map$country,"country.name","iso3c")
dt_ins_map.code<-data.frame(code,dt_ins_map)
dt_ins_map.code <- na.omit(dt_ins_map.code)
```

```{r}
dt_ins %>% 
  filter(country=="United States") %>% 
  select(c(current_employee_estimate)) %>%
  sum() -> employees_us
```

```{r}
dt_ins %>% 
  mutate(is_us = case_when(country == "United States" ~ "USA",
                           country != "United States" ~ "Other countries")) %>% 
 ggplot() +
 aes(x = year_founded) +
 geom_histogram(bins = 45L, fill = my_colors[2],color="#2c3e50") +
 theme_minimal() +
 facet_wrap(vars(is_us))+
 theme_abyss()+
 theme(plot.margin = unit(c(1, 2, 1, 1), "cm")) + 
 theme(plot.title = element_text(size = 22, family = my_font)) + 
 theme(plot.subtitle = element_text(size = 13, family = my_font)) + 
 theme(plot.caption  = element_text(size = 12, family = my_font)) + 
 theme(axis.text = element_text(family = my_font, size = 13)) + 
 theme(panel.grid.major.x = element_blank())+
  labs(x = "Year founded", y = "Number of companies",
       title = "Figure 1: Nuclear Electricity Power in GWh by Country, 2019",
       subtitle = paste0("US has ",dt_ins_map.code$n[1], " with ", employees_us, " employees"),
       caption = "Source: Kaggle.com") 
  

```

```{r}
dt_ins %>% 
  filter(year_founded >= 2000) %>% 
  mutate(is_us = case_when(country == "United States" ~ "USA",
                           country != "United States" ~ "Other countries")) %>% 
  select(is_us,year_founded) %>% 
  count(year_founded,is_us) %>% 
  pivot_wider(names_from = is_us,values_from = n) %>% 
  arrange(desc(year_founded)) %>% 
  kbl() %>%
  kable_material_dark()
```

```{r}
dt_ins %>% 
  arrange(year_founded) %>% 
  slice(1:20)
```




```{r}
dt_ins_map.code %>% 
  arrange(desc(n)) %>% 
  slice(1:20) %>% 
  ggplot(aes(reorder(country,n),n)) +
  geom_col(fill = my_colors[2]) + 
  coord_flip() + 
  labs(x = NULL, y = NULL, title = "Figure 1: Nuclear Electricity Power in GWh by Country, 2019",
       subtitle = paste0("US has ",dt_ins_map.code$n[1], " with ", employees_us, " employees"),
       caption = "Source: Kaggle.com") +
  geom_text(aes(label = n), color = "white",hjust=-0.1, size = 4) + 
  my_theme() 
```
```{r}

```

```{r}
dt_ins_map.code %>% 
  mutate(hover = paste0("Number of insurance companies in ",country, ": ", n)) %>% 
  plot_geo() %>% 
  add_trace(z = ~n,
            zmin=100,
            zmax=dt_ins_map.code$n[2],
            color = ~n,
            locations = ~code,
            colorscale = "Reds",
            text = ~hover,
            hoverinfo ="text") %>% 
  colorbar(title = 'Number of companies') %>% 
  layout(title = '2018 Global <br> Source:<a href="https://www.kaggle.com/peopledatalabssf/free-7-million-company-dataset"> Kaggle.com </a>',
         font = list(family = "my_font"))

```

```{r}
dt_ins %>% 
  filter( country == "United States")  %>%  
  left_join(states, by.x = state, by.y =state) %>% 
  count(code) %>% 
  arrange(desc(n)) %>% 
  left_join(states, by.x = state, by.y =state) %>% 
  mutate(hover = paste0("Number of insurance companies in ",state, ": ", n))-> dt_ins_us
dt_ins_us
```

```{r}
graph_properties <- list(
  scope = 'usa',
  showland = TRUE,
  landcolor = toRGB("white"),
  color = toRGB("white")
)

font = list(
  family = "DM Sans",
  size = 15,
  color = "black"
)

label = list(
  bgcolor = "#EEEEEE",
  bordercolor = "transparent",
  font = font
)


plot_geo(dt_ins_us,locationmode ="USA-states") %>% 
  add_trace(z = ~n,
            color = ~n,
            colorscale = "Portland",
            locations = ~code,
            text = ~hover,
            hoverinfo ="text")%>% 
  layout(geo = graph_properties,
         title = "Amount of insurance companies in USA by state",
         font = list(family = "DM Sans")) %>%
  colorbar(title = 'Number of companies') %>% 
  config(displayModeBar = FALSE) 
```







































